# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PWA Tips
author: Gokul & Hemanth
email: pwa.tips@gmail.com
description: Read about latest PWA's, Brower updates, new API's and its improvements in your inbox.
logo: /images/icons/android-chrome-512x512.png
baseurl: ""
url: "https://pwa.tips" # the base hostname & protocol for your site
twitter_username: pwatips
github_username: code-kotis
disqus_shortname: 

# Build settings
markdown: kramdown
highlighter: rouge

# Server Config options
livereload: true # You no longer need to include --livereload

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-autoprefixer

autoprefixer:
  only_production: true

twitter:
  username: pwatips

social:
  name: PWA Tips
  links:
    - https://twitter.com/pwatips
    - https://www.facebook.com/pwatips
    - https://plus.google.com/+pwatips

facebook:
  app_id: 181993332292671

google_site_verification: gkGQ_1z_l3jOk9fNspG7wTKoTaYCVGHs6f7AfCRZtac
