# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: PWA Tips
author: 
email: pwa.tips@gmail.com
description: 
logo: 
baseurl: ""
url: "https://pwa.tips" # the base hostname & protocol for your site
twitter_username: pwatips
github_username: 
disqus_shortname: 

# Build settings
markdown: kramdown
highlighter: rouge

# Server Config options
livereload: true # You no longer need to include --livereload

gems:
  - jekyll-seo-tag
  - jekyll-sitemap
  
twitter:
  username: 

social:
  name: PWA Tips
  links:
    - https://twitter.com/pwatips
    - https://www.facebook.com/
    - https://plus.google.com/

facebook:
  app_id: 

google_site_verification: 
